//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffPlan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Plan
    {
        public System.DateTime Week { get; set; }
        public string LOB { get; set; }
        public string Plan { get; set; }
        public Nullable<decimal> FTE_Definition { get; set; }
        public Nullable<decimal> Planned_Attrition { get; set; }
        public Nullable<decimal> Planned_Occupancy { get; set; }
        public Nullable<decimal> Planned_Shrinkage { get; set; }
        public Nullable<decimal> Planned_OOC_Shrinkage { get; set; }
        public Nullable<decimal> Planned_ABS { get; set; }
        public Nullable<decimal> Planned_Time_Off { get; set; }
        public Nullable<decimal> Planned_LOA { get; set; }
        public Nullable<decimal> Planned_IC_Shrinkage { get; set; }
        public Nullable<decimal> Planned_Break { get; set; }
        public Nullable<decimal> Planned_Coach { get; set; }
        public Nullable<decimal> Planned_Lead { get; set; }
        public Nullable<decimal> Planned_Meeting { get; set; }
        public Nullable<decimal> Planned_Personal { get; set; }
        public Nullable<decimal> Planned_Preshift { get; set; }
        public Nullable<decimal> Planned_Project { get; set; }
        public Nullable<decimal> Planned_System { get; set; }
        public Nullable<decimal> Planned_Training { get; set; }
        public Nullable<decimal> Planned_Unaccounted_Time { get; set; }
        public Nullable<decimal> Production_HC { get; set; }
        public Nullable<decimal> Tenured_HC { get; set; }
        public Nullable<decimal> Non_Tenured_HC { get; set; }
        public Nullable<decimal> Nesting_HC { get; set; }
        public Nullable<decimal> Training_HC { get; set; }
        public Nullable<decimal> Production_Hours { get; set; }
        public Nullable<decimal> Tenured_Hours { get; set; }
        public Nullable<decimal> Non_Tenured_Hours { get; set; }
        public Nullable<decimal> Nesting_Hours { get; set; }
        public Nullable<decimal> Training_Hours { get; set; }
        public Nullable<decimal> Production_AHT { get; set; }
        public Nullable<decimal> Tenured_AHT { get; set; }
        public Nullable<decimal> Non_Tenured_AHT { get; set; }
        public Nullable<decimal> Nesting_AHT { get; set; }
        public Nullable<decimal> Training_AHT { get; set; }
        public Nullable<decimal> Production_Concurrency { get; set; }
        public Nullable<decimal> Tenured_Concurrency { get; set; }
        public Nullable<decimal> Non_Tenured_Concurrency { get; set; }
        public Nullable<decimal> Nesting_Concurrency { get; set; }
        public Nullable<decimal> Training_Concurrency { get; set; }
        public Nullable<decimal> Production_FTE { get; set; }
        public Nullable<decimal> Tenured_FTE { get; set; }
        public Nullable<decimal> Non_Tenured_FTE { get; set; }
        public Nullable<decimal> Nesting_FTE { get; set; }
        public Nullable<decimal> Training_FTE { get; set; }
        public Nullable<decimal> Production_Capacity { get; set; }
        public Nullable<decimal> Tenured_Capacity { get; set; }
        public Nullable<decimal> Non_Tenured_Capacity { get; set; }
        public Nullable<decimal> Nesting_Capacity { get; set; }
        public Nullable<decimal> Training_Capacity { get; set; }
        public Nullable<decimal> Production_Seats { get; set; }
        public Nullable<decimal> Training_Seats { get; set; }
    }
}
